//------------------------------------------------------------------------
// Copyright(c) 2025 My Plug-in Company.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

//! Plain project version file generated by cmake
#include "projectversion.h"

#define stringOriginalFilename "Spectr.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription "Spectr VST3 (64Bit)"
#else
#define stringFileDescription "Spectr VST3"
#endif
#define stringCompanyName "Maro VST Company\0"
#define stringLegalCopyright "Copyright(c) 2025 Maro VST Company."
#define stringLegalTrademarks \
  "VST is a trademark of Steinberg Media Technologies GmbH"
